export { Navbar, Footer, Download } from './common';
export { Shopper, Business, Hero } from './home';
export { CliqueHero, HowItWorks } from './clique';
export { CardHero } from './card';
export { Banner, OnCredit, Sell, PaymentLink } from './getPaid';
export { default as CareerHero } from './careers';
export { default as Faq } from './faq';
export { default as Contact } from './contactus';
export { Accept, LoginComponent } from './acceptmoney';
export { Price } from './pricing';
